workspace:
  base: /go
  path: src/github.com/appleboy/drone-gitlab-ci

clone:
  git:
    image: plugins/git
    depth: 50
    tags: true

pipeline:
  lint:
    image: golang:1.11
    pull: true
    group: test
    commands:
      - make vet
      - make lint
      - make test-vendor
      - make misspell-check

  test:
    image: golang:1.11
    pull: true
    group: test
    commands:
      - make test
      - make coverage

  codecov:
    image: robertstettner/drone-codecov
    secrets: [ codecov_token ]
    when:
      event: [ push, pull_request ]
      status: [ success ]

  publish_latest:
    image: plugins/docker
    repo: ${DRONE_REPO}
    tags: [ 'latest' ]
    secrets: [ docker_username, docker_password ]
    when:
      event: [ push ]
      branch: [ master ]
      local: false

  release:
    image: golang:1.11
    pull: true
    commands:
      - make release
    when:
      event: [ tag ]
      local: false

  publish_tag:
    image: plugins/docker
    repo: ${DRONE_REPO}
    tags: [ '${DRONE_TAG}' ]
    secrets: [ docker_username, docker_password ]
    group: release
    when:
      event: [ tag ]
      branch: [ refs/tags/* ]
      local: false

  release_tag:
    image: plugins/github-release
    secrets: [ github_release_api_key ]
    group: release
    files:
      - dist/release/*
    when:
      event: [ tag ]
      branch: [ refs/tags/* ]
      local: false
